### ISSUE TITLE
filta desolves into noise

### ISSUE THREAD

**Issue by magnetophon** [openAVproductions/openAV-ArtyFX#12]
In A3/4 jalv and ingen (all my hosts) the current git version of artyFX:

with the freq in the upper halve, I slowly get more and more digital noise, until after 3 sec, I have just noise.
This only happens with a sound as input. Any sound.

**Comment by hypsinom** [comment]
Is it possible to correct this bug. I really want to use this plugin for use with mixxx.

**Comment by harryhaaren** [comment]
Ive attempted to reproduce this, not able to get this issue to show up. Closing, if you can still reproduce please reopen with more detail on setup/config/host/audio being used.

**Comment by autumncheney** [comment]
i encountered this bug too, it happens when the knob is set exactly in the middle

i'm using the latest build of zrythm with jack

**Comment by harryhaaren** [comment]
Thanks for reporting @autumncheney, interesting info that this occurs when the control is exactly in the middle - this is new info for me, thanks.
