### ISSUE TITLE
manual broken Link

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-ArtyFX#19]
In the manual-File there is a broken Link to the OpenAV Release System.

**Comment by harryhaaren** [comment]
can you provide a link? I'm not sure which one you mean, or what it should be pointing at. Cheers!

**Comment by georgkrause** [comment]
https://github.com/openAVproductions/openAV-ArtyFX/blob/master/manual.md
There is in the Second passage is a link to the release system...

**Comment by harryhaaren** [comment]
Thanks - ah yes that manual.. will fix tommorrow. Cheers!
