### ISSUE TITLE
Della: Noises when Loaded in Ardour 5 's track

### ISSUE THREAD

**Issue by sub26nico** [openAVproductions/openAV-ArtyFX#23]
I often have terrible noises with Della at the opening of the plugin window in Ardour 5 
when I load Della in an Ardour's track.

**Comment by georgkrause** [comment]
same here. i assume this is because della gets a click as input when loading in a track which gets delayed pretty fast.

**Comment by harryhaaren** [comment]
Thanks for reporting, unfortunatly I don't understand exactly what you're saying triggers the issue:
- Loading Della DSP and UI into a track in Ardour 5 
- Opening Della UI in Ardour 5 (where the plugin DSP was already loaded on track)

Assuming that loading a new DSP on a track was the issue, I've pushed a commit, please re-test with latest and see if you can reproduce.

**Comment by sub26nico** [comment]
The noise appears when "Loading Della DSP and UI into a track in Ardour 5".
I'll try the new version ASAP.

**Comment by georgkrause** [comment]
i tested until ardour crashes. i assume ardour 5 is still too buggy to use :(
tomorrow i will do some further tests with ardour 4.

**Comment by sub26nico** [comment]
I tested with new commits and it's seem to be ok, no more noises at loading Della in a track.
Test made with the same project, and others too, on two computers.
I can't reproduce the issues now.

**Comment by harryhaaren** [comment]
Thanks for reporting, I'm tracking the progress of releasing this fix here:
https://github.com/openAVproductions/openAV-ArtyFX/milestone/2

Thanks again, I'll mark this as closed now.
