### ISSUE TITLE
build flags from environment ignored

### ISSUE THREAD

**Issue by falkTX** [openAVproductions/openAV-ArtyFX#26]
(also, building with SSE removes the previous flags)

when you use cmake, please do not use this:
`SET(CMAKE_C_FLAGS "-msse2 -mfpmath=sse")`
use this instead:
`SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -msse2 -mfpmath=sse")`

because of this at the moment artyfx plugins are built without the flags 'g -Wall -O1 -Wno-unused-variable' that you even set on your file, because SSE is enabled by default and overrides previous flags.

the same happens with the linker flags.

**Comment by harryhaaren** [comment]
Thanks @falkTX, I'll fix them when I'm on the dev machine.
