### ISSUE TITLE
a new open av doppler fx

### ISSUE THREAD

**Issue by Reaper10** [openAVproductions/openAV-ArtyFX#27]
I don't know if I can suggest a new plugin. I would love to open av productions Doppler fx plugin. 
Something like this is what I am asking  ---------->https://youtu.be/MCyTBNlZK-I?t=1m52s

**Comment by harryhaaren** [comment]
Hey Reaper10.

Technically DSP wise, I think the effect is time-based playback, time-stretching, and various "doppler" effects - which is actually just changing the speed of the playback. I don't see myself creating such an FX for ArtyFX, as ArtyFX is intended to be more "live performance" effects not so much cinematic effects..

Sorry for the delay - I remember watching the link, and I thought I posted a reply - but obviously I never did - apologies for that! Thanks for the request, -Harry
