### ISSUE TITLE
Reverse playback as a FX plugin

### ISSUE THREAD

**Issue by Reaper10** [openAVproductions/openAV-ArtyFX#30]
Would you make a audio reverse plugin that when it is on it makes play in reverse? It would be cool make it have wet dray knob for the effect and a on off switch.

**Comment by harryhaaren** [comment]
Hi Reaper,

I'm not developing new ArtyFX much recently, so I don't see this getting onto the prioritized list, sorry. I'll leave this issue open, and update the title a bit to be more descriptive!

Thanks for your input, -Harry

**Comment by harryhaaren** [comment]
Closing request - not planning to add new effects. This issue will remain in the issues tab - will reopen if considering adding new plugins.
