### ISSUE TITLE
Missing dependencies  - libsndfile1-dev libsamplerate0-dev 

### ISSUE THREAD

**Issue by hellocatfood** [openAVproductions/openAV-ArtyFX#32]
I was following the build instructions to install artyfx on Ubuntu 19.04 and noticed the readme is missing the following packages: libsndfile1-dev libsamplerate0-dev. Can the readme be updated to include them?

**Comment by harryhaaren** [comment]
Fixed by your own PR here https://github.com/openAVproductions/openAV-ArtyFX/pull/33 Thanks again!
