### ISSUE TITLE
Benchmark library dep is not listed

### ISSUE THREAD

**Issue by Skrylar** [openAVproductions/openAV-ArtyFX#36]
There is a benchmark library used and mandated by the meson script, however which library that is has no mention in the readme.

**Comment by harryhaaren** [comment]
Hi Skrylar, indeed the official binary should not require benchmark to be installed/available, but it is nice to have them build on a development machine. Commit d594d80 already fixed the mandatory requirement, making it optional instead. I'll close this issue now, thanks for reporting.
